-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Gorothi Worldbreaker", {
	[240277] = {"cyan","green","orange","red"},
	[244106] = "orange",
	[244410] = {"blue","yellow"},
	[244761] = "red",
	[244969] = "orange",
	[246220] = {"blue","purple"},
})

BigWigs:AddSounds("Gorothi Worldbreaker", {
	[240277] = {"alarm","info","long"},
	[244106] = "alarm",
	[244410] = "warning",
	[244761] = "alert",
	[244969] = "warning",
	[246220] = {"alarm","warning"},
})

BigWigs:AddColors("Felhounds of Sargeras", {
	[244050] = "orange",
	[244054] = {"blue","red"},
	[244055] = {"blue","red"},
	[244056] = "yellow",
	[244057] = "yellow",
	[244072] = {"blue","yellow"},
	[244131] = "yellow",
	[244768] = {"blue","orange"},
	[245022] = "blue",
	[245098] = "red",
	[248815] = "blue",
	[248819] = "blue",
	[251356] = "cyan",
	[251445] = "red",
	[254429] = "orange",
})

BigWigs:AddSounds("Felhounds of Sargeras", {
	[244050] = "warning",
	[244054] = "warning",
	[244055] = "warning",
	[244056] = "alert",
	[244057] = "alert",
	[244072] = "warning",
	[244131] = "alert",
	[244768] = "warning",
	[245022] = "alert",
	[245098] = "alarm",
	[248815] = "warning",
	[248819] = "warning",
	[251356] = "info",
	[251445] = "alarm",
	[254429] = "warning",
})

BigWigs:AddColors("Antoran High Command", {
	[244172] = "blue",
	[244625] = "orange",
	[244737] = {"blue","yellow"},
	[244892] = {"blue","purple"},
	[244910] = {"blue","green"},
	[245161] = "yellow",
	[245227] = "cyan",
	[245546] = "red",
	[246505] = "orange",
	[253039] = "blue",
})

BigWigs:AddSounds("Antoran High Command", {
	[244172] = "warning",
	[244625] = "warning",
	[244737] = "warning",
	[244892] = "warning",
	[244910] = "info",
	[245161] = "info",
	[245227] = "long",
	[245546] = "alarm",
	[246505] = "alert",
	[253039] = "alert",
})

BigWigs:AddColors("Portal Keeper Hasabel", {
	[243983] = "red",
	[244000] = "orange",
	[244016] = {"blue","orange"},
	[244598] = "yellow",
	[244607] = "orange",
	[244613] = "blue",
	[244689] = "cyan",
	[244849] = "blue",
	[244926] = {"blue","orange"},
	[245040] = {"blue","yellow"},
	[245050] = "yellow",
	[245075] = "orange",
	[245118] = "blue",
	[245504] = "orange",
	[246075] = "red",
	[246316] = "red",
	[246911] = "blue",
	[246925] = "blue",
	[246929] = "blue",
	[255805] = "red",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Portal Keeper Hasabel", {
	[243983] = "warning",
	[244000] = "alert",
	[244016] = "alarm",
	[244598] = "alert",
	[244607] = "alarm",
	[244613] = "info",
	[244689] = "info",
	[244849] = "info",
	[244926] = "warning",
	[245040] = "warning",
	[245050] = "alert",
	[245075] = "info",
	[245118] = "info",
	[245504] = "alarm",
	[246075] = "alarm",
	[246316] = "alarm",
	[246911] = "info",
	[246925] = "info",
	[246929] = "info",
	[255805] = "alarm",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Eonar the Life-Binder", {
	[248332] = {"blue","red"},
	[248861] = "red",
	[249121] = {"green","red"},
	[250048] = {"cyan","green"},
	[250140] = "blue",
	[250691] = "blue",
	[250693] = "blue",
	["warp_in"] = "yellow",
})

BigWigs:AddSounds("Eonar the Life-Binder", {
	[248332] = "alarm",
	[248861] = "warning",
	[249121] = {"info","warning"},
	[250048] = {"info","long"},
	[250140] = "alarm",
	[250691] = "alarm",
	[250693] = "alarm",
	["warp_in"] = "alert",
})

BigWigs:AddColors("Imonar the Soulhunter", {
	[247367] = {"blue","purple"},
	[247376] = "yellow",
	[247687] = {"blue","purple"},
	[247923] = "yellow",
	[248068] = "yellow",
	[248070] = "orange",
	[248254] = "orange",
	[250255] = {"blue","purple"},
	[254244] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Imonar the Soulhunter", {
	[247367] = {"alarm","warning"},
	[247376] = "alert",
	[247687] = {"alarm","warning"},
	[247923] = "alert",
	[248068] = "alert",
	[248070] = "warning",
	[248254] = "warning",
	[250255] = "alarm",
	[254244] = {"alarm","alert"},
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Kin'garoth", {
	[246516] = {"cyan","green"},
	[246664] = "red",
	[246686] = {"blue","orange"},
	[246698] = {"blue","orange"},
	[246833] = {"cyan","orange"},
	[248214] = {"cyan","red"},
	[248375] = "orange",
	[249680] = {"blue","orange"},
	[254919] = {"blue","purple"},
	[254926] = {"blue","cyan","yellow"},
})

BigWigs:AddSounds("Kin'garoth", {
	[246516] = {"info","long"},
	[246664] = "alarm",
	[246686] = "warning",
	[246698] = "warning",
	[246833] = {"info","warning"},
	[248214] = {"alarm","info"},
	[248375] = "warning",
	[249680] = "warning",
	[254919] = {"alert","warning"},
	[254926] = {"alert","info"},
})

BigWigs:AddColors("Varimathras", {
	[-16350] = "orange",
	[243960] = "purple",
	[243961] = "blue",
	[243999] = {"blue","yellow"},
	[244042] = {"blue","red"},
	[244094] = {"blue","green","orange"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Varimathras", {
	[-16350] = "alarm",
	[243960] = "warning",
	[243961] = "alarm",
	[243999] = "alert",
	[244042] = "alarm",
	[244094] = {"info","warning"},
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("The Coven of Shivarra", {
	[244899] = {"blue","cyan"},
	[245518] = "blue",
	[245586] = {"blue","green"},
	[245627] = {"blue","yellow"},
	[246329] = "yellow",
	[250648] = "orange",
	[250757] = {"blue","yellow"},
	[252861] = {"blue","red"},
	[253203] = "red",
	[253520] = {"blue","red"},
	[253650] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
	["torment_of_the_titans"] = {"cyan","orange","red"},
})

BigWigs:AddSounds("The Coven of Shivarra", {
	[244899] = "info",
	[245518] = "info",
	[245586] = "alarm",
	[245627] = "alert",
	[246329] = "alert",
	[250648] = "alarm",
	[250757] = "alarm",
	[252861] = {"alarm","alert"},
	[253203] = "info",
	[253520] = "alarm",
	[253650] = "alert",
	["berserk"] = "alarm",
	["stages"] = "long",
	["torment_of_the_titans"] = {"info","warning"},
})

BigWigs:AddColors("Aggramar", {
	[244693] = {"blue","yellow"},
	[245301] = "orange",
	[245458] = "yellow",
	[245463] = "red",
	[245983] = "red",
	[245990] = {"blue","purple"},
	[245994] = {"blue","red"},
	[246037] = "red",
	[254452] = {"blue","red"},
	[255058] = "red",
	[255061] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = {"cyan","green"},
	["track_ember"] = "cyan",
})

BigWigs:AddSounds("Aggramar", {
	[244693] = "alert",
	[245301] = "warning",
	[245458] = "alert",
	[245463] = "alarm",
	[245983] = "warning",
	[245990] = "alarm",
	[245994] = "warning",
	[246037] = "warning",
	[254452] = "warning",
	[255058] = "alarm",
	[255061] = "warning",
	["berserk"] = "alarm",
	["stages"] = "long",
	["track_ember"] = "info",
})

BigWigs:AddColors("Argus the Unmaker", {
	[-17077] = "yellow",
	[248165] = "orange",
	[248167] = "blue",
	[248317] = "cyan",
	[248396] = {"blue","orange"},
	[248499] = {"blue","cyan","yellow"},
	[250669] = {"blue","red"},
	[251570] = {"blue","orange"},
	[252616] = {"blue","orange","red"},
	[252729] = {"blue","orange"},
	[255199] = {"blue","green"},
	[255200] = "blue",
	[255594] = "green",
	[255826] = "yellow",
	[255935] = "yellow",
	[256388] = "red",
	[256399] = "yellow",
	[256544] = {"green","red"},
	[257214] = "green",
	[257296] = "yellow",
	[257911] = "blue",
	[257966] = {"blue","orange"},
	[258039] = {"blue","cyan","yellow"},
	[258068] = {"blue","orange"},
	[258834] = "yellow",
	[258838] = {"blue","cyan","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["combinedBurstAndBomb"] = "red",
	["stages"] = "green",
})

BigWigs:AddSounds("Argus the Unmaker", {
	[-17077] = "alert",
	[248165] = "warning",
	[248167] = "alarm",
	[248317] = "alert",
	[248396] = "warning",
	[248499] = {"alarm","alert","warning"},
	[250669] = "alarm",
	[251570] = "warning",
	[252616] = "alarm",
	[252729] = "warning",
	[255199] = "long",
	[255200] = "info",
	[255594] = {"info","long"},
	[255826] = "alarm",
	[255935] = "alert",
	[256388] = "warning",
	[256399] = "alert",
	[256544] = {"info","warning"},
	[257214] = "long",
	[257296] = "alarm",
	[257911] = "alarm",
	[257966] = "warning",
	[258039] = {"alarm","alert","warning"},
	[258068] = "warning",
	[258834] = "info",
	[258838] = {"alarm","alert","warning"},
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Antorus Trash", {
	[245861] = "blue",
	[246199] = "blue",
	[246209] = "yellow",
	[249212] = "red",
	[249297] = {"blue","red"},
	[251612] = "blue",
	[252621] = {"blue","yellow"},
	[252743] = "red",
	[252760] = {"blue","orange"},
	[252797] = {"blue","orange"},
	[253600] = {"blue","green","orange"},
	[254122] = {"blue","orange"},
	[254500] = "red",
	[254512] = "blue",
})

BigWigs:AddSounds("Antorus Trash", {
	[245861] = "alert",
	[246199] = "alert",
	[246209] = "long",
	[249212] = "warning",
	[249297] = "warning",
	[251612] = "alert",
	[252621] = "alarm",
	[252743] = "long",
	[252760] = "warning",
	[252797] = "warning",
	[253600] = {"alarm","info"},
	[254122] = "alarm",
	[254500] = {"long","warning"},
	[254512] = "alert",
})

BigWigs:AddColors("Matron Folnuna", {
	[247361] = {"blue","cyan"},
	[247379] = {"blue","orange"},
	[247443] = "red",
	[254147] = "yellow",
})

BigWigs:AddSounds("Matron Folnuna", {
	[247361] = "alarm",
	[247379] = {"long","warning"},
	[247443] = "alarm",
	[254147] = "alert",
})

BigWigs:AddColors("Mistress Alluradel", {
	[247517] = "blue",
	[247544] = {"blue","orange"},
	[247549] = "orange",
	[247604] = "yellow",
})

BigWigs:AddSounds("Mistress Alluradel", {
	[247517] = "info",
	[247544] = "alert",
	[247549] = "warning",
	[247604] = "alarm",
})

BigWigs:AddColors("Inquisitor Meto", {
	[247492] = {"blue","yellow"},
	[247495] = {"blue","yellow"},
	[247585] = {"green","orange"},
	[247632] = "blue",
})

BigWigs:AddSounds("Inquisitor Meto", {
	[247492] = {"alarm","alert"},
	[247495] = {"alert","warning"},
	[247585] = {"info","long"},
	[247632] = "alarm",
})

BigWigs:AddColors("Sothanar", {
	[247410] = {"blue","cyan","red"},
	[247416] = "yellow",
	[247437] = {"blue","orange"},
	[247698] = "yellow",
})

BigWigs:AddSounds("Sothanar", {
	[247410] = {"alarm","info","warning"},
	[247416] = "alert",
	[247437] = "warning",
	[247698] = "long",
})

BigWigs:AddColors("Occularus", {
	[247318] = {"blue","red"},
	[247320] = "orange",
	[247325] = "yellow",
	[247332] = {"blue","yellow"},
	[247393] = {"blue","cyan"},
})

BigWigs:AddSounds("Occularus", {
	[247318] = "alarm",
	[247320] = "warning",
	[247325] = "info",
	[247332] = {"alarm","alert"},
	[247393] = {"alarm","long"},
})

BigWigs:AddColors("Pit Lord Vilemus", {
	[247731] = "red",
	[247733] = "orange",
	[247739] = {"blue","cyan","yellow"},
})

BigWigs:AddSounds("Pit Lord Vilemus", {
	[247731] = "long",
	[247733] = "warning",
	[247739] = {"alarm","alert"},
})

BigWigs:AddColors("Apocron", {
	[241458] = "orange",
	[241498] = "yellow",
	[241518] = {"blue","green","red"},
})

BigWigs:AddSounds("Apocron", {
	[241458] = "warning",
	[241498] = "long",
	[241518] = {"alarm","info"},
})

BigWigs:AddColors("Brutallus", {
	[233484] = "orange",
	[233515] = "red",
	[233566] = "yellow",
})

BigWigs:AddSounds("Brutallus", {
	[233484] = "warning",
	[233515] = "alert",
	[233566] = "info",
})

BigWigs:AddColors("Calamir", {
	[217877] = {"blue","yellow"},
	[217893] = "red",
	[217925] = {"blue","yellow"},
	[217966] = "red",
	[217986] = "red",
	[218012] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Calamir", {
	[217877] = "alert",
	[217893] = "alarm",
	[217925] = {"alarm","long"},
	[217966] = "warning",
	[217986] = "alert",
	[218012] = "long",
	["stages"] = "info",
})

BigWigs:AddColors("Drugon the Frostblood", {
	[219493] = "red",
	[219542] = "yellow",
	[219602] = {"blue","green","orange"},
	[219803] = {"blue","green"},
})

BigWigs:AddSounds("Drugon the Frostblood", {
	[219493] = "alert",
	[219542] = "warning",
	[219602] = {"alarm","long"},
})

BigWigs:AddColors("Flotsam", {
	[220295] = {"blue","green"},
	[220340] = "yellow",
	[223317] = "red",
	[223373] = "orange",
})

BigWigs:AddSounds("Flotsam", {
	[220295] = "alarm",
	[220340] = "warning",
	[223317] = "alert",
	[223373] = "long",
})

BigWigs:AddColors("Humongris", {
	[216428] = {"blue","yellow"},
	[216430] = "orange",
	[216432] = {"blue","red"},
	[216467] = "green",
	[216476] = "blue",
	[216817] = {"blue","red"},
})

BigWigs:AddSounds("Humongris", {
	[216428] = "alarm",
	[216430] = "info",
	[216432] = "alert",
	[216467] = "long",
	[216476] = "alert",
	[216817] = "warning",
})

BigWigs:AddColors("Levantus", {
	[217206] = "blue",
	[217235] = "orange",
	[217249] = "yellow",
	[217344] = "green",
})

BigWigs:AddSounds("Levantus", {
	[217206] = "alarm",
	[217235] = "warning",
	[217249] = "long",
	[217344] = "alert",
})

BigWigs:AddColors("Malificus", {
	[233570] = "yellow",
	[233614] = "orange",
	[233850] = "blue",
	[234452] = "orange",
})

BigWigs:AddSounds("Malificus", {
	[233570] = "info",
	[233614] = "warning",
	[233850] = "alert",
	[234452] = "alarm",
})

BigWigs:AddColors("Na'zak the Fiend", {
	[219349] = "orange",
	[219591] = "yellow",
	[219813] = "red",
	[219861] = "green",
})

BigWigs:AddSounds("Na'zak the Fiend", {
	[219349] = "info",
	[219591] = "alert",
	[219813] = "long",
	[219861] = "warning",
})

BigWigs:AddColors("Nithogg", {
	[-13327] = "red",
	[212836] = "yellow",
	[212852] = "orange",
	[212867] = "red",
	[212887] = {"blue","green"},
})

BigWigs:AddSounds("Nithogg", {
	[-13327] = "alarm",
	[212836] = "alert",
	[212852] = "warning",
	[212867] = "info",
	[212887] = "warning",
})

BigWigs:AddColors("Shar'thos", {
	[215806] = "blue",
	[215821] = "red",
	[215876] = "blue",
	[216043] = {"blue","yellow"},
	[216044] = "orange",
})

BigWigs:AddSounds("Shar'thos", {
	[215806] = "alert",
	[215821] = "info",
	[215876] = "alert",
	[216043] = "alarm",
	[216044] = "warning",
})

BigWigs:AddColors("Si'vash", {
	[233968] = "orange",
	[233996] = "orange",
	[241433] = "yellow",
})

BigWigs:AddSounds("Si'vash", {
	[233968] = "long",
	[233996] = "warning",
	[241433] = "alarm",
})

BigWigs:AddColors("The Soultakers", {
	[213420] = "green",
	[213532] = "red",
	[213588] = {"blue","red"},
	[213606] = "yellow",
	[213625] = "blue",
	[213665] = "orange",
})

BigWigs:AddSounds("The Soultakers", {
	[213420] = "long",
	[213532] = "warning",
	[213588] = "alert",
	[213606] = "warning",
	[213625] = "alarm",
	[213665] = "info",
})

BigWigs:AddColors("Withered J'im", {
	[223614] = "orange",
	[223623] = "yellow",
	[223715] = "cyan",
})

BigWigs:AddSounds("Withered J'im", {
	[223614] = "alert",
	[223623] = "alarm",
	[223715] = "info",
})

BigWigs:AddColors("Skorpyron", {
	[-13767] = "cyan",
	[204275] = "red",
	[204284] = {"blue","green"},
	[204316] = "red",
	[204372] = "yellow",
	[204448] = "cyan",
	[204459] = "green",
	[204471] = "orange",
	[204744] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Skorpyron", {
	[-13767] = "info",
	[204275] = "alarm",
	[204284] = "warning",
	[204316] = "alarm",
	[204372] = "long",
	[204459] = "info",
	[204471] = "alert",
	[204744] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Chronomatic Anomaly", {
	[-13022] = "cyan",
	[206607] = {"blue","red"},
	[206609] = {"blue","orange","yellow"},
	[206617] = {"blue","red"},
	[207228] = "orange",
	[207871] = "blue",
	[207976] = {"cyan","orange","red"},
	[211927] = "yellow",
	[212099] = {"blue","green"},
	[219815] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Chronomatic Anomaly", {
	[-13022] = "info",
	[206607] = "warning",
	[206609] = "alarm",
	[206617] = "alert",
	[207228] = "alert",
	[207871] = "alert",
	[207976] = {"alarm","long"},
	[211927] = "long",
	[212099] = "info",
	[219815] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Trilliax", {
	[206488] = "blue",
	[206641] = {"blue","red"},
	[206788] = "orange",
	[206820] = "yellow",
	[207502] = {"blue","yellow"},
	[207630] = "red",
	[208910] = "blue",
	[211615] = {"blue","red"},
	[214670] = "red",
	[215062] = "orange",
	[215066] = "cyan",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Trilliax", {
	[206488] = "alert",
	[206641] = "warning",
	[206788] = "alarm",
	[206820] = "alarm",
	[207502] = "info",
	[207630] = "long",
	[208910] = "warning",
	[211615] = "warning",
	[214670] = "alert",
	[215062] = "alarm",
	[215066] = "long",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Spellblade Aluriel", {
	[212492] = {"blue","red"},
	[212530] = "red",
	[212531] = {"blue","yellow"},
	[212587] = {"blue","orange","yellow"},
	[212647] = {"blue","red"},
	[212735] = "red",
	[212736] = "blue",
	[213083] = "red",
	[213148] = {"blue","orange"},
	[213275] = "red",
	[213278] = "blue",
	[213390] = "red",
	[213504] = "blue",
	[213520] = {"blue","red"},
	[213564] = "red",
	[213567] = "red",
	[213569] = "orange",
	[213852] = "red",
	[213853] = "red",
	[230403] = "green",
	[230414] = "blue",
	[230504] = "orange",
	[230901] = "green",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Spellblade Aluriel", {
	[212492] = {"alarm","warning"},
	[212530] = "alarm",
	[212531] = "alert",
	[212587] = "alert",
	[212647] = "warning",
	[212735] = "alarm",
	[212736] = "alert",
	[213275] = "alarm",
	[213278] = "alert",
	[213390] = "alarm",
	[213504] = "alert",
	[213520] = "alert",
	[213564] = "info",
	[213567] = "info",
	[213569] = "info",
	[213852] = "alarm",
	[213853] = "info",
	[230403] = "long",
	[230414] = "alert",
	[230901] = "info",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Tichondrius", {
	[206365] = "cyan",
	[206466] = {"blue","cyan"},
	[206480] = {"blue","yellow"},
	[208230] = {"blue","orange"},
	[212794] = {"blue","green"},
	[213238] = "orange",
	[213531] = "red",
	[216024] = {"blue","orange"},
	[216027] = "blue",
	[216040] = {"blue","yellow"},
	["adds"] = "cyan",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Tichondrius", {
	[206365] = "long",
	[206466] = "info",
	[206480] = "warning",
	[208230] = "long",
	[212794] = "alarm",
	[213238] = "info",
	[213531] = "long",
	[216024] = "alarm",
	[216027] = "alert",
	[216040] = "warning",
	["adds"] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Krosus", {
	[205344] = {"blue","orange"},
	[205370] = "yellow",
	[205420] = "yellow",
	[205862] = "red",
	[206677] = {"blue","orange"},
	[208203] = "red",
	["smashingBridge"] = "red",
})

BigWigs:AddSounds("Krosus", {
	[205344] = "warning",
	[205370] = "info",
	[205420] = "info",
	[205862] = "alert",
	[206677] = "warning",
	[208203] = "alert",
	["smashingBridge"] = "alert",
})

BigWigs:AddColors("High Botanist Tel'arn", {
	[218148] = "red",
	[218304] = {"blue","orange","yellow"},
	[218342] = "blue",
	[218438] = "red",
	[218503] = {"blue","yellow"},
	[218774] = "orange",
	[218809] = {"blue","red"},
	[218927] = {"blue","orange","red"},
	[219235] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("High Botanist Tel'arn", {
	[218148] = "long",
	[218304] = "alarm",
	[218342] = "info",
	[218438] = "alert",
	[218503] = "warning",
	[218774] = "alert",
	[218809] = "alert",
	[218927] = {"alarm","long"},
	[219235] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Star Augur Etraeus", {
	[205408] = {"blue","green","red","yellow"},
	[205649] = "blue",
	[205984] = {"blue","orange"},
	[206388] = {"blue","red"},
	[206398] = "blue",
	[206464] = "yellow",
	[206517] = "red",
	[206589] = "blue",
	[206936] = {"blue","yellow"},
	[206949] = "red",
	[207439] = "red",
	[207720] = "yellow",
	[214167] = {"blue","orange"},
	[214335] = {"blue","orange"},
	[216909] = "red",
	[222761] = {"orange","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Star Augur Etraeus", {
	[205408] = {"info","warning"},
	[205649] = "warning",
	[205984] = "warning",
	[206388] = "warning",
	[206398] = "alert",
	[206517] = "alarm",
	[206936] = "warning",
	[206949] = "alarm",
	[207439] = "alarm",
	[207720] = "warning",
	[214167] = "warning",
	[214335] = "warning",
	[216909] = "alarm",
	[222761] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Grand Magistrix Elisande", {
	[209165] = "blue",
	[209166] = "green",
	[209170] = {"blue","yellow"},
	[209244] = {"blue","orange","red"},
	[209597] = {"blue","red"},
	[209615] = {"blue","orange"},
	[209617] = "yellow",
	[209620] = "red",
	[209971] = "red",
	[209973] = {"blue","yellow"},
	[210022] = "orange",
	[211261] = {"blue","red"},
	[211887] = {"blue","orange"},
	[221864] = "red",
	[228877] = "yellow",
	[229889] = {"orange","red"},
	["expedient_elemental"] = "cyan",
	["recursive_elemental"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Grand Magistrix Elisande", {
	[209165] = "long",
	[209166] = "long",
	[209170] = {"alert","info"},
	[209244] = {"alarm","alert"},
	[209597] = "alarm",
	[209615] = "warning",
	[209617] = "info",
	[209620] = "alert",
	[209971] = "alert",
	[209973] = "long",
	[210022] = "alert",
	[211261] = "alarm",
	[211887] = "warning",
	[221864] = "alert",
	[228877] = "alarm",
	[229889] = "alarm",
	["expedient_elemental"] = "info",
	["recursive_elemental"] = "info",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Gul'dan", {
	[167935] = "red",
	[206219] = {"cyan","orange"},
	[206310] = {"blue","green"},
	[206514] = {"blue","red"},
	[206675] = "red",
	[206744] = "orange",
	[206840] = {"blue","yellow"},
	[206847] = {"blue","orange"},
	[206883] = "orange",
	[206896] = {"blue","orange"},
	[206983] = {"blue","red"},
	[207938] = "yellow",
	[208545] = "yellow",
	[208672] = "yellow",
	[208802] = "blue",
	[209011] = {"blue","cyan","red","yellow"},
	[209270] = {"blue","cyan","orange"},
	[210296] = {"blue","green"},
	[210339] = "blue",
	[211152] = {"blue","cyan","orange"},
	[211439] = "yellow",
	[212258] = "yellow",
	[212568] = {"blue","orange"},
	[217830] = {"blue","green"},
	[220957] = {"blue","orange"},
	[221408] = "orange",
	[221486] = "red",
	[221606] = "blue",
	[221781] = "blue",
	[221891] = {"blue","red"},
	[227008] = "red",
	[227009] = "cyan",
	[227556] = "green",
	[229945] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["manifest"] = "yellow",
	["nightorb"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Gul'dan", {
	[167935] = "long",
	[206219] = "alarm",
	[206310] = "warning",
	[206514] = {"alarm","alert"},
	[206675] = "warning",
	[206744] = "alert",
	[206840] = {"alarm","info"},
	[206847] = "alarm",
	[206883] = "long",
	[206896] = "warning",
	[206983] = "info",
	[207938] = "info",
	[208545] = "alert",
	[208672] = "long",
	[208802] = "info",
	[209011] = {"info","warning"},
	[209270] = {"alert","info"},
	[211152] = "alert",
	[211439] = "warning",
	[212258] = "info",
	[212568] = "alarm",
	[217830] = "info",
	[220957] = {"alert","warning"},
	[221408] = "alert",
	[221486] = "alarm",
	[221606] = "warning",
	[221781] = "alarm",
	[227008] = "alarm",
	[227009] = "long",
	[227556] = "info",
	[229945] = "alarm",
	["berserk"] = "alarm",
	["manifest"] = "alert",
	["nightorb"] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Nighthold Trash", {
	[221160] = "orange",
	[221164] = "red",
	[221344] = {"blue","red"},
	[223655] = {"blue","red"},
	[224440] = "orange",
	[224510] = "yellow",
	[224568] = "yellow",
	[224572] = "blue",
	[224632] = {"blue","orange"},
	[224944] = {"blue","red"},
	[224982] = {"blue","red"},
	[225105] = {"blue","yellow"},
	[225390] = "blue",
	[225412] = "orange",
	[225800] = "red",
	[225845] = "blue",
	[225856] = "blue",
	[225857] = {"blue","red"},
	[225927] = "yellow",
	[230438] = "red",
	[230482] = "yellow",
	[230488] = "blue",
	[230994] = {"blue","yellow"},
	[231005] = "red",
	[231086] = {"blue","orange"},
})

BigWigs:AddSounds("Nighthold Trash", {
	[221160] = "long",
	[221164] = "alarm",
	[221344] = "warning",
	[223655] = "warning",
	[224440] = "warning",
	[224510] = "long",
	[224568] = "long",
	[224572] = "alert",
	[224632] = "warning",
	[224944] = "long",
	[224982] = "warning",
	[225105] = "alert",
	[225390] = "alert",
	[225412] = "info",
	[225800] = "info",
	[225845] = "warning",
	[225856] = "alert",
	[225857] = "warning",
	[225927] = "info",
	[230438] = "alarm",
	[230482] = "info",
	[230488] = "alert",
	[230994] = "warning",
	[231005] = "long",
	[231086] = "long",
})

BigWigs:AddColors("Nythendra", {
	[202977] = "orange",
	[203045] = "blue",
	[203096] = {"blue","red"},
	[203552] = "cyan",
	[204463] = {"blue","orange"},
	[204504] = "blue",
	[225943] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Nythendra", {
	[202977] = "alarm",
	[203045] = "alert",
	[203096] = "warning",
	[203552] = "info",
	[204463] = "warning",
	[204504] = "warning",
	[225943] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Il'gynoth", {
	[208689] = "blue",
	[208697] = {"cyan","yellow"},
	[208929] = {"blue","cyan","orange"},
	[209469] = {"blue","red"},
	[210099] = {"blue","yellow"},
	[210984] = {"blue","red"},
	[212886] = "blue",
	[215128] = {"blue","yellow"},
	[215234] = "orange",
	[218415] = {"green","orange"},
	[223121] = "cyan",
	["nightmare_horror"] = "red",
	["shriveled_eyestalk"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Il'gynoth", {
	[208689] = "alarm",
	[208697] = "info",
	[208929] = {"alert","info"},
	[210099] = "info",
	[210984] = "warning",
	[212886] = "alert",
	[215128] = {"alert","warning"},
	[218415] = {"alarm","long"},
	[223121] = "info",
	["nightmare_horror"] = "info",
	["shriveled_eyestalk"] = "info",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Elerethe Renferal", {
	[210547] = "red",
	[210864] = {"blue","orange"},
	[210948] = "cyan",
	[212364] = "red",
	[212707] = "yellow",
	[213124] = "blue",
	[214348] = "yellow",
	[215300] = {"blue","yellow"},
	[215443] = {"blue","orange"},
	[215582] = "yellow",
	[218124] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Elerethe Renferal", {
	[210547] = "alarm",
	[210864] = {"long","warning"},
	[210948] = "info",
	[212364] = "info",
	[212707] = "long",
	[213124] = "alert",
	[214348] = "alarm",
	[215300] = "warning",
	[215443] = {"long","warning"},
	[215582] = "long",
	[218124] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Ursoc", {
	[197943] = {"blue","red"},
	[197969] = "orange",
	[198006] = {"blue","red"},
	[198388] = {"cyan","orange"},
	[204859] = {"blue","yellow"},
	[205611] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Ursoc", {
	[197943] = {"alarm","warning"},
	[197969] = "alarm",
	[198006] = "warning",
	[198388] = {"info","long"},
	[204859] = {"info","warning"},
	[205611] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Dragons of Nightmare", {
	[-13460] = "cyan",
	[-12809] = {"blue","green","red"},
	[203028] = "orange",
	[203147] = "red",
	[203770] = {"blue","yellow"},
	[203787] = {"blue","yellow"},
	[203888] = "red",
	[204040] = "blue",
	[204078] = "red",
	[204100] = "orange",
	[204245] = "yellow",
	[204767] = "yellow",
	[205298] = "yellow",
	[205300] = "yellow",
	[205341] = "orange",
	[207573] = "red",
})

BigWigs:AddSounds("Dragons of Nightmare", {
	[-13460] = "long",
	[-12809] = {"info","warning"},
	[203028] = "info",
	[203147] = "alert",
	[203770] = {"alarm","alert"},
	[203787] = "alert",
	[203888] = "alert",
	[204040] = "warning",
	[204078] = "alarm",
	[204100] = "long",
	[204245] = "alarm",
	[204767] = "long",
	[205298] = "long",
	[205300] = "info",
	[205341] = "alarm",
})

BigWigs:AddColors("Cenarius", {
	[210279] = {"blue","green","orange"},
	[210290] = "orange",
	[210346] = {"blue","green","orange"},
	[211192] = {"blue","yellow"},
	[211368] = {"blue","orange","red"},
	[211471] = {"blue","red"},
	[211989] = "blue",
	[212681] = "green",
	[212726] = {"cyan","orange"},
	[213162] = "orange",
	[214505] = {"blue","orange"},
	[214529] = {"blue","orange"},
	[214876] = "red",
	[214884] = "yellow",
	[226821] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Cenarius", {
	[210279] = {"info","warning"},
	[210290] = "alarm",
	[210346] = {"alarm","info"},
	[211192] = "alert",
	[211368] = "alarm",
	[211471] = "alert",
	[211989] = "alert",
	[212681] = "alert",
	[212726] = "info",
	[213162] = "alert",
	[214505] = "alarm",
	[214529] = "warning",
	[214876] = "alert",
	[214884] = "info",
	[226821] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Xavius", {
	[205588] = "yellow",
	[205741] = "blue",
	[205771] = "blue",
	[205843] = "green",
	[206005] = "blue",
	[206651] = {"blue","orange"},
	[207409] = {"blue","red"},
	[207830] = "yellow",
	[208431] = "blue",
	[209034] = {"blue","red"},
	[209158] = {"blue","orange"},
	[209443] = {"blue","orange"},
	[210264] = "yellow",
	[211634] = "blue",
	[211802] = {"blue","red"},
	[224508] = {"blue","yellow"},
	[226194] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Xavius", {
	[205588] = "info",
	[205741] = "alert",
	[205771] = "long",
	[205843] = "long",
	[206005] = "info",
	[206651] = "warning",
	[207409] = "alarm",
	[208431] = "alarm",
	[209034] = {"alert","warning"},
	[209158] = "warning",
	[209443] = "alarm",
	[210264] = "info",
	[211634] = "alert",
	[211802] = "alert",
	[224508] = "info",
	[226194] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Emerald Nightmare Trash", {
	[221028] = "blue",
	[221059] = "orange",
	[222719] = {"blue","green"},
	["totem"] = "red",
})

BigWigs:AddSounds("Emerald Nightmare Trash", {
	[221028] = "warning",
	[221059] = "info",
	[222719] = "alert",
	["totem"] = "long",
})

BigWigs:AddColors("Goroth", {
	[231363] = {"blue","orange","yellow"},
	[232249] = {"blue","red"},
	[233062] = "orange",
	[233279] = {"blue","yellow"},
	[233514] = "red",
	[234346] = "blue",
	[238588] = "orange",
})

BigWigs:AddSounds("Goroth", {
	[231363] = {"alarm","warning"},
	[232249] = "warning",
	[233062] = "warning",
	[233279] = "alarm",
	[233514] = "alert",
	[234346] = "alarm",
	[238588] = "warning",
})

BigWigs:AddColors("Demonic Inquisition", {
	[233104] = "blue",
	[233426] = "yellow",
	[233431] = {"blue","orange"},
	[233441] = "red",
	[233895] = {"blue","yellow"},
	[233983] = "red",
	[234015] = "yellow",
	[235230] = "red",
	[236283] = "blue",
	[239401] = "red",
	[248671] = {"orange","red"},
	[248713] = {"blue","red"},
	["fixate"] = "blue",
})

BigWigs:AddSounds("Demonic Inquisition", {
	[233104] = "info",
	[233426] = "alert",
	[233431] = "alert",
	[233441] = "warning",
	[233895] = {"alert","info"},
	[233983] = "alert",
	[234015] = "long",
	[235230] = "warning",
	[236283] = "alert",
	[239401] = "alarm",
	[248671] = "alarm",
	[248713] = "warning",
	["fixate"] = "long",
})

BigWigs:AddColors("Harjatan the Bludger", {
	[231729] = {"blue","red"},
	[231768] = "blue",
	[231854] = "orange",
	[231998] = {"blue","orange"},
	[232061] = {"orange","red"},
	[232174] = "orange",
	[232192] = "red",
	[233429] = {"blue","orange"},
	[240319] = "red",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Harjatan the Bludger", {
	[231729] = "alarm",
	[231768] = "alert",
	[231854] = "warning",
	[231998] = "warning",
	[232061] = {"alarm","alert"},
	[232174] = "warning",
	[232192] = "alert",
	[233429] = "alarm",
	[240319] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Mistress Sassz'ine", {
	[230139] = {"blue","red"},
	[230201] = {"blue","orange","yellow"},
	[230227] = "orange",
	[230358] = "red",
	[230384] = {"blue","yellow"},
	[230959] = "blue",
	[232722] = "red",
	[232827] = "red",
	[232913] = "yellow",
	[234621] = {"green","red"},
	[239362] = "blue",
	[239436] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Mistress Sassz'ine", {
	[230139] = "warning",
	[230201] = {"alarm","warning"},
	[230227] = "alarm",
	[230358] = "warning",
	[230384] = "alert",
	[230959] = "alert",
	[232722] = "warning",
	[232827] = "warning",
	[232913] = "info",
	[234621] = {"info","warning"},
	[239362] = "alert",
	[239436] = "warning",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Sisters of the Moon", {
	[233263] = "yellow",
	[236305] = {"blue","orange"},
	[236442] = {"blue","yellow"},
	[236480] = "red",
	[236519] = {"blue","yellow"},
	[236541] = {"blue","yellow"},
	[236547] = "red",
	[236550] = {"blue","orange"},
	[236603] = {"blue","yellow"},
	[236694] = "orange",
	[236697] = "yellow",
	[236712] = {"blue","yellow"},
	[237351] = "blue",
	[239264] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Sisters of the Moon", {
	[233263] = "alarm",
	[236305] = "warning",
	[236442] = {"alarm","alert"},
	[236480] = "warning",
	[236519] = "alert",
	[236541] = {"info","warning"},
	[236547] = "warning",
	[236550] = "alarm",
	[236603] = "warning",
	[236694] = "alert",
	[236697] = "alert",
	[236712] = "alert",
	[237351] = "alert",
	[239264] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("The Desolate Host", {
	[235907] = {"blue","yellow"},
	[235924] = {"blue","orange"},
	[235927] = "yellow",
	[236072] = "red",
	[236131] = "blue",
	[236241] = "blue",
	[236361] = "blue",
	[236459] = {"blue","green"},
	[236513] = {"green","yellow"},
	[236515] = {"blue","yellow"},
	[236542] = "red",
	[236544] = "red",
	[236548] = {"blue","yellow"},
	[236678] = "red",
	[238570] = {"blue","orange","yellow"},
	[239006] = "cyan",
})

BigWigs:AddSounds("The Desolate Host", {
	[235907] = "alert",
	[235924] = "alarm",
	[235927] = "alert",
	[236072] = "warning",
	[236131] = "alarm",
	[236241] = "alert",
	[236361] = "alert",
	[236459] = {"info","long","warning"},
	[236513] = {"info","warning"},
	[236515] = "warning",
	[236542] = "warning",
	[236544] = "warning",
	[236548] = "info",
	[236678] = "warning",
	[238570] = {"alarm","alert","info"},
	[239006] = "info",
})

BigWigs:AddColors("Maiden of Vigilance", {
	[234891] = {"green","orange","yellow"},
	[235028] = "green",
	[235117] = "blue",
	[235267] = "yellow",
	[235271] = {"cyan","green","red"},
	[238028] = "blue",
	[238408] = "blue",
	[239153] = "yellow",
	[241593] = "cyan",
	[241635] = "orange",
	[241636] = "orange",
	[248812] = "red",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Maiden of Vigilance", {
	[234891] = {"alert","long"},
	[235028] = "info",
	[235117] = "alarm",
	[235267] = "alert",
	[235271] = {"info","warning"},
	[238028] = "alert",
	[238408] = "alert",
	[239153] = "alert",
	[241593] = "info",
	[241635] = "alert",
	[241636] = "alert",
	[248812] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Fallen Avatar", {
	[233556] = "red",
	[233856] = {"green","orange","yellow"},
	[234059] = {"blue","orange","yellow"},
	[234418] = "red",
	[235572] = "orange",
	[236494] = {"blue","orange","yellow"},
	[236528] = "orange",
	[236604] = {"blue","yellow"},
	[236684] = "yellow",
	[239132] = "orange",
	[239207] = "yellow",
	[239212] = "blue",
	[239739] = {"blue","yellow"},
	[240623] = "red",
	[240728] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
	["energy_leak"] = "yellow",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Fallen Avatar", {
	[233556] = "warning",
	[233856] = {"alarm","info"},
	[234059] = {"alarm","alert"},
	[234418] = "alarm",
	[235572] = "warning",
	[236494] = {"alert","warning"},
	[236528] = "warning",
	[236604] = {"alarm","alert"},
	[236684] = "info",
	[239132] = "warning",
	[239207] = "alert",
	[239212] = "alert",
	[239739] = "alarm",
	[240623] = "warning",
	[240728] = "warning",
	["berserk"] = "alarm",
	["energy_leak"] = "info",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Kil'jaeden", {
	[-15543] = "yellow",
	[235059] = "orange",
	[236378] = {"blue","orange"},
	[236710] = {"blue","orange"},
	[237590] = {"blue","orange"},
	[238430] = {"blue","red"},
	[238505] = {"blue","yellow"},
	[238999] = "orange",
	[239932] = "red",
	[240262] = "blue",
	[240910] = "red",
	[241564] = "yellow",
	[241721] = "blue",
	[243982] = "red",
	[244856] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Kil'jaeden", {
	[-15543] = "info",
	[235059] = "warning",
	[236378] = "alert",
	[236710] = "alert",
	[237590] = "alert",
	[238430] = "warning",
	[238505] = "alarm",
	[238999] = "long",
	[239932] = {"alarm","info"},
	[240262] = "alert",
	[240910] = "warning",
	[241564] = "alarm",
	[241721] = {"alert","long"},
	[243982] = "alarm",
	[244856] = "alert",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Tomb of Sargeras Trash", {
	[239741] = {"blue","orange"},
	[240169] = "red",
	[240176] = "blue",
	[240599] = {"blue","yellow"},
	[240735] = {"blue","orange"},
	[241169] = "blue",
	[241171] = {"blue","yellow"},
	[241254] = "yellow",
	[241262] = "blue",
	[241267] = {"blue","orange"},
	[241289] = "red",
	[241301] = "yellow",
	[241367] = {"blue","yellow"},
	[241374] = "yellow",
	[241446] = "red",
	[241465] = {"blue","green","yellow"},
	[241480] = "orange",
	[241646] = "green",
	[241675] = {"blue","orange"},
	[241703] = "blue",
	[241716] = {"blue","green","yellow"},
	[241742] = {"blue","yellow"},
	[242909] = "orange",
})

BigWigs:AddSounds("Tomb of Sargeras Trash", {
	[239741] = "alarm",
	[240169] = "alarm",
	[240176] = "alert",
	[240599] = "alert",
	[240735] = "alarm",
	[241169] = "alert",
	[241171] = "warning",
	[241254] = "long",
	[241262] = "alert",
	[241267] = "alarm",
	[241289] = "warning",
	[241301] = "info",
	[241367] = "warning",
	[241374] = "warning",
	[241446] = "long",
	[241465] = "warning",
	[241480] = "warning",
	[241675] = "alert",
	[241703] = "alert",
	[241716] = {"info","warning"},
	[241742] = "warning",
	[242909] = "long",
})

BigWigs:AddColors("Odyn-TrialOfValor", {
	[-14495] = "blue",
	[-14404] = {"cyan","green"},
	[197961] = "blue",
	[227475] = "blue",
	[227503] = {"green","yellow"},
	[227626] = {"blue","yellow"},
	[227629] = "orange",
	[227807] = "blue",
	[228012] = "orange",
	[228018] = "red",
	[228029] = {"blue","red"},
	[228162] = {"blue","red"},
	[228171] = {"blue","green"},
	[228918] = {"blue","red"},
	[229584] = {"blue","green"},
	[231350] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Odyn-TrialOfValor", {
	[-14495] = "warning",
	[-14404] = "info",
	[197961] = "warning",
	[227475] = "alarm",
	[227503] = "long",
	[227629] = "alert",
	[227807] = "alarm",
	[228012] = "alert",
	[228018] = "alarm",
	[228029] = "alarm",
	[228162] = "alarm",
	[228171] = "long",
	[228918] = "alarm",
	[229584] = "info",
	[231350] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Guarm-TrialOfValor", {
	[227514] = "yellow",
	[227816] = "red",
	[227883] = "orange",
	[228187] = "yellow",
	[228228] = {"blue","orange"},
	[228248] = {"blue","orange"},
	[228253] = {"blue","orange"},
	[228744] = "red",
	[228810] = "cyan",
	[228818] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Guarm-TrialOfValor", {
	[227816] = "long",
	[227883] = "info",
	[228187] = "warning",
	[228228] = "alarm",
	[228248] = "alarm",
	[228253] = "alarm",
	[228744] = "alert",
	[228810] = "alarm",
	[228818] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Helya-TrialOfValor", {
	[167910] = "cyan",
	[193367] = "blue",
	[227967] = "red",
	[227982] = {"blue","orange"},
	[228054] = {"blue","green","yellow"},
	[228127] = "blue",
	[228300] = "red",
	[228390] = "yellow",
	[228519] = "orange",
	[228565] = "red",
	[228611] = "orange",
	[228619] = "red",
	[228633] = "yellow",
	[228730] = "orange",
	[228854] = "green",
	[228872] = "red",
	[229119] = {"blue","orange"},
	[230197] = "blue",
	[230267] = {"blue","orange"},
	[232450] = {"blue","yellow"},
	[232488] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
	["tentacle_far"] = "orange",
	["tentacle_near"] = "orange",
})

BigWigs:AddSounds("Helya-TrialOfValor", {
	[167910] = "long",
	[193367] = "warning",
	[227967] = "alarm",
	[227982] = "alarm",
	[228054] = {"alert","warning"},
	[228127] = "alert",
	[228300] = "info",
	[228390] = "alert",
	[228519] = "alarm",
	[228565] = "alarm",
	[228611] = "long",
	[228619] = "long",
	[228633] = "alert",
	[228730] = "long",
	[228854] = "info",
	[228872] = "long",
	[229119] = {"alarm","warning"},
	[230197] = "alarm",
	[230267] = {"alarm","warning"},
	[232450] = "long",
	[232488] = "alarm",
	["berserk"] = "alarm",
	["stages"] = "long",
	["tentacle_far"] = "long",
	["tentacle_near"] = "long",
})
